# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KonanaVision' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KonanaVision

  target 'KonanaVisionTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'KonanaVision-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KonanaVision-tvOS

  target 'KonanaVision-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
